version: '3.8'
services:
  db:
    image: postgres:15
    container_name: javdb-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: javdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '55432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
